'use strict';mix_d("AmazonHomepageSolitaireCards__quad-multi-asin-card-v2:quad-multi-asin-card-v2__joFDycfu","exports tslib @p/A @c/metrics @c/scoped-dom @c/aui-utils".split(" "),function(n,p,y,q,z,r){function t(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var g=t(y),u=t(z),A=function(a){return 9<a?String(a):"0".concat(a)},l=function(a){if(0>=a)return"00:00";var b=Math.floor(a/36E5);a=[Math.floor(a/6E4%60),Math.floor(a/1E3%60)];0<b&&a.unshift(b);return a.map(A).join(":")},D=function(a,
b){var e=Array.prototype.slice.call(a.querySelectorAll("[data-component='badge-countdown-timer']")).map(function(c){if(!c.dataset.targetTime&&!c.dataset.absoluteTargetTime)return function(){};B(c);return C(c,b)});return function(){return e.forEach(function(c){return c()})}},E=function(a){Array.prototype.slice.call(a.querySelectorAll("[data-component='dui-badge']")).forEach(function(b){b&&32<b.offsetHeight&&(null===b||void 0===b?void 0:b.setAttribute("data-align","vertical"))})},C=function(a,b){if("true"===
a.dataset.initialized||!a.dataset.absoluteTargetTime)return function(){};a.dataset.initialized="true";var e=Number(a.dataset.absoluteTargetTime),c=e-Date.now();0<c&&(a.innerText=l(c));var d=b(function(){var f=e-Date.now();0>=f?(a.innerText=l(0),clearInterval(d)):a.innerText=l(f)},500);return function(){a.dataset.initialized="false";clearInterval(d)}},B=function(a){if(!a.dataset.absoluteTargetTime){var b=Number(a.dataset.targetTime),e=Date.now();b=Number.isNaN(b)?e:b+e;a.dataset.absoluteTargetTime=
String(b)}},v={},m=function(a,b,e){void 0===b&&(b="");void 0===e&&(e=1);b=a+b;v.hasOwnProperty(b)||(v[b]=!0,q.count(a,(q.count(a)||0)+e))},H=function(a){m(g["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");var b=function(c,d){c={$event:{preventDefault:g["default"].$.noop,stopPropagation:g["default"].$.noop},$target:c.getContent().find('[data-a-tab-name="'+d+'"]'),data:{name:"energyEfficiencyTabSet"}};g["default"].trigger("a:declarative:a-tabs:click",
c)},e=function(c,d){var f=c&&c.$event,k=c&&c.data||{},F=k.activeTabName,G=k.modalHeight,w=k.name;f&&f.preventDefault&&f.preventDefault();f&&f.stopPropagation&&f.stopPropagation();f=d.get(w);f||(g["default"].on("a:popover:beforeShow:"+w,function(h){h.popover&&h.popover.getContent&&(h=h.popover.getContent(),h.find(".a-manually-loaded").parent().css("min-height",G),g["default"].loadDescendantImagesManually(h))}),f=d.create(c.$target,k));f.show();b(f,F)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",
function(c){g["default"].declarative("card-energy-efficiency-secondary-view","click",function(d){m("Card:EERU:SharedLib:mobile:click",d&&d.data&&d.data.name||"");e(d,c)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",function(c){g["default"].declarative("card-energy-efficiency-modal","click",function(d){m("Card:EERU:SharedLib:desktop:click",d&&d.data&&d.data.name||"");e(d,c)})})},I=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(b){var e=g["default"].$;
e(".energyEfficiencyContainer").each(function(c,d){c=e(d).find(".energyEfficiencyProductFicheLabel").first();d=e(d).find("svg").first();c.parent().outerHeight()>d.outerHeight()&&(c.removeClass("a-size-small"),c.addClass("a-size-micro"),c.parent().outerHeight()>d.outerHeight()&&c.parent().css("line-height","10px"))})})},J=function(a){return 9<a?String(a):"0"+a},x=function(a){if(0>=a)return"00:00";var b=Math.floor(a/36E5);a=[Math.floor(a/6E4%60),Math.floor(a/1E3%60)];0<b&&a.unshift(b);return a.map(J).join(":")},
L=function(a){Array.prototype.slice.call(a.getElementsByClassName("badge-countdown-timer")).forEach(function(b){(new K(b)).start()})},K=function(){function a(b){this.timerElement=b;this.msToEvent=parseInt(b.dataset.time,10);this.timerElement.innerText=x(this.msToEvent)}a.prototype.start=function(){var b=this;isNaN(this.msToEvent)||(this.counterStartTime=Date.now(),this.counterInterval=r.interval(function(){return b.updateTime()},500))};a.prototype.updateTime=function(){var b=Date.now()-this.counterStartTime;
0>=this.msToEvent-b&&clearInterval(this.counterInterval);this.timerElement.innerText=x(this.msToEvent-b)};return a}();n._operationNames=[];n.card=function(){return p.__awaiter(void 0,void 0,void 0,function(){return p.__generator(this,function(a){a=window.P;H(a);I(a);a=u["default"].cardRoot;D(a,r.interval);E(a);L(u["default"].cardRoot);return[2]})})}});
