'use strict';mix_d("AmazonHomepageSolitaireCards__multi-asin-thumbnails:multi-asin-thumbnails__aApZvsrI","exports tslib @c/metrics @c/scoped-dom @p/A @c/dom @p/a-truncate @c/aui-utils".split(" "),function(l,k,m,z,A,B,C,q){function n(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var h=n(z),D=n(A),E=n(C),F=function(a){return 9<a?String(a):"0".concat(a)},p=function(a){if(0>=a)return"00:00";var b=Math.floor(a/36E5);a=[Math.floor(a/6E4%60),Math.floor(a/1E3%60)];0<b&&a.unshift(b);return a.map(F).join(":")},
I=function(a,b){b=G(a,b);H(a);return b},G=function(a,b){var d=Array.prototype.slice.call(a.querySelectorAll("[data-component='badge-countdown-timer']")).map(function(c){if(!c.dataset.targetTime&&!c.dataset.absoluteTargetTime)return function(){};J(c);return K(c,b)});return function(){return d.forEach(function(c){return c()})}},H=function(a){Array.prototype.slice.call(a.querySelectorAll("[data-component='dui-badge']")).forEach(function(b){b&&32<b.offsetHeight&&(null===b||void 0===b?void 0:b.setAttribute("data-align",
"vertical"))})},K=function(a,b){if("true"===a.dataset.initialized||!a.dataset.absoluteTargetTime)return function(){};a.dataset.initialized="true";var d=Number(a.dataset.absoluteTargetTime),c=d-Date.now();0<c&&(a.innerText=p(c));var e=b(function(){var g=d-Date.now();0>=g?(a.innerText=p(0),clearInterval(e)):a.innerText=p(g)},500);return function(){a.dataset.initialized="false";clearInterval(e)}},J=function(a){if(!a.dataset.absoluteTargetTime){var b=Number(a.dataset.targetTime),d=Date.now();b=Number.isNaN(b)?
d:b+d;a.dataset.absoluteTargetTime=String(b)}},r=function(a){Array.prototype.slice.call(a.getElementsByClassName("a-truncate")).forEach(function(b){return E["default"].get(B.unscope(b)).update()})},L=function(a){return 9<a?String(a):"0"+a},t=function(a){if(0>=a)return"00:00";var b=Math.floor(a/36E5);a=[Math.floor(a/6E4%60),Math.floor(a/1E3%60)];0<b&&a.unshift(b);return a.map(L).join(":")},N=function(a){Array.prototype.slice.call(a.getElementsByClassName("badge-countdown-timer")).forEach(function(b){(new M(b)).start()})},
M=function(){function a(b){this.timerElement=b;this.msToEvent=parseInt(b.dataset.time,10);this.timerElement.innerText=t(this.msToEvent)}a.prototype.start=function(){var b=this;isNaN(this.msToEvent)||(this.counterStartTime=Date.now(),this.counterInterval=q.interval(function(){return b.updateTime()},500))};a.prototype.updateTime=function(){var b=Date.now()-this.counterStartTime;0>=this.msToEvent-b&&clearInterval(this.counterInterval);this.timerElement.innerText=t(this.msToEvent-b)};return a}(),O=function(a,
b){(a=a.querySelector(".a-cardui-footer"))&&a.addEventListener("click",function(){var d=b+":seeMoreClick",c=void 0;void 0===c&&(c=1);m.count(d,+(m.count(d)||0)+c)})},x=function(a){var b;P(a);var d=f("_multi-asin-thumbnails_style_productHeroBlock__3VTqk"),c=f("_multi-asin-thumbnails_style_productHeroLucidWrapper__wuqu7");try{for(var e=k.__values(d.entries()),g=e.next();!g.done;g=e.next()){var u=k.__read(g.value,2),Q=u[0],v=u[1];v.classList.contains("_multi-asin-thumbnails_style_activeHero__1E5kM")&&
(v.classList.remove("_multi-asin-thumbnails_style_activeHero__1E5kM"),c[Q].classList.remove("_multi-asin-thumbnails_style_activeHeroLucidWrapper__2WBDb"))}}catch(R){var w={error:R}}finally{try{g&&!g.done&&(b=e.return)&&b.call(e)}finally{if(w)throw w.error;}}d[a].classList.add("_multi-asin-thumbnails_style_activeHero__1E5kM");c[a].classList.add("_multi-asin-thumbnails_style_activeHeroLucidWrapper__2WBDb");r(d[a])},P=function(a){var b=f("imageLoadingSpinner"+a)[0];b&&!b.classList.contains("aok-hidden")&&
(D["default"].loadImageManually(f("manualLoadAsinHeroImage"+a)),b=f("manualLoadAsinHeroImage"+a)[0],b.complete?y(a):b.addEventListener("load",function(){y(a)}))},y=function(a){var b=f("imageLoadingSpinner"+a)[0];a=f("manualLoadAsinHeroImage"+a)[0];b.classList.add("aok-hidden");a.classList.remove("_multi-asin-thumbnails_style_loadingHeroImage__2C5f6")},f=function(a){return Array.prototype.slice.call(h["default"].cardRoot.getElementsByClassName(a))};l._operationNames=[];l.card=function(){return k.__awaiter(void 0,
void 0,void 0,function(){var a,b;return k.__generator(this,function(d){r(h["default"].cardRoot);a=function(c){f("thumbnail"+c)[0].addEventListener("click",function(e){m.count("thumbnailClick",1);e.preventDefault();f("_multi-asin-thumbnails_style_productHeroBlock__3VTqk")[c].classList.contains("_multi-asin-thumbnails_style_activeHero__1E5kM")||x(c)})};for(b=0;4>b;b++)a(b);O(h["default"].cardRoot,"multi-asin-thumbnails");N(h["default"].cardRoot);I(h["default"].cardRoot,q.interval);return[2]})})};l.changeActiveHero=
x});
