'use strict';mix_d("P13NSCCards__p13n-rvi:p13n-rvi__TRSCDDVa","exports tslib @p/A @c/metrics @c/aui-carousel @c/dom @c/remote-operations @c/scoped-dom @p/a-carousel-framework @c/logger @c/aui-untrusted-ajax @c/browser-operations".split(" "),function(F,r,N,B,O,P,Q,R,S,T,U,V){function x(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var p=x(N),W=x(O),G=x(Q),u=x(R),X=x(S),z=x(T),Y=x(U),Z=x(V),H={},C=function(a,c,b){void 0===c&&(c="");void 0===b&&(b=1);c=a+c;H.hasOwnProperty(c)||(H[c]=
!0,B.count(a,(B.count(a)||0)+b))},aa=function(a){C(p["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");var c=function(d,e){d={$event:{preventDefault:p["default"].$.noop,stopPropagation:p["default"].$.noop},$target:d.getContent().find('[data-a-tab-name="'+e+'"]'),data:{name:"energyEfficiencyTabSet"}};p["default"].trigger("a:declarative:a-tabs:click",d)},b=function(d,e){var f=d&&d.$event,g=d&&d.data||{},n=g.activeTabName,l=g.modalHeight,t=g.name;
f&&f.preventDefault&&f.preventDefault();f&&f.stopPropagation&&f.stopPropagation();f=e.get(t);f||(p["default"].on("a:popover:beforeShow:"+t,function(h){h.popover&&h.popover.getContent&&(h=h.popover.getContent(),h.find(".a-manually-loaded").parent().css("min-height",l),p["default"].loadDescendantImagesManually(h))}),f=e.create(d.$target,g));f.show();c(f,n)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",function(d){p["default"].declarative("card-energy-efficiency-secondary-view",
"click",function(e){C("Card:EERU:SharedLib:mobile:click",e&&e.data&&e.data.name||"");b(e,d)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",function(d){p["default"].declarative("card-energy-efficiency-modal","click",function(e){C("Card:EERU:SharedLib:desktop:click",e&&e.data&&e.data.name||"");b(e,d)})})},ba=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(c){var b=p["default"].$;b(".energyEfficiencyContainer").each(function(d,e){d=b(e).find(".energyEfficiencyProductFicheLabel").first();
e=b(e).find("svg").first();d.parent().outerHeight()>e.outerHeight()&&(d.removeClass("a-size-small"),d.addClass("a-size-micro"),d.parent().outerHeight()>e.outerHeight()&&d.parent().css("line-height","10px"))})})},ca={ctiList:["Website/Personalization/Report a Problem CX"],category:"Website",type:"Personalization",item:"Report a Problem CX",folder:"9c9c97c9-6f69-4dba-a55d-26045c6a3068",group:"P13N Report a Problem CX"},da=[{ctiList:["Website/Personalization/Similarities","Website/Detail Page/Similarities"],
category:"Website",type:"Personalization",item:"Similarities",folder:"4d16d05d-9a17-4b36-b8fe-9ee159ff81de",group:"Similarities"}],ia=function(a){var c=u["default"].cardRoot.querySelector(".p13n-report-flag"),b=Z["default"].setup();b.define("showFlag","mouseover",function(){c.classList.remove("p13n-report-flag-hide")});b.define("hideFlag","mouseout",function(){c.classList.add("p13n-report-flag-hide")});b.attach("showFlag",a);b.attach("hideFlag",a);var d=u["default"].cardRoot.querySelector(".internal-flag-form"),
e=d.querySelector(".internal-flag-env-data").dataset,f=d.querySelector(".internal-flag-title-text"),g=d.querySelector(".internal-flag-description").firstElementChild,n=d.querySelector(".internal-flag-alias"),l=d.querySelector(".internal-flag-response-message"),t=function(h){h.preventDefault();h=function(q){return!q||!q.trim()};if(h(f.value)||h(g.value)||h(n.value))return D(l,!1,"Something went wrong. One of the required fields was missing."),!1;h=u["default"].cardRoot.querySelectorAll(".a-dynamic-image");
var k;if(k=u["default"].cardRoot.querySelector(".a-carousel-heading")){var v=ea(a,h.length);k="Internal user reported issue '"+f.value+"' with widget: "+k.innerText}else v=fa(a),k="Internal user reported issue '"+f.value+"'";h=ha(h,v,g.value,n.value,e);var m=ca;da.forEach(function(q){q.ctiList.includes(e.cti)&&(m=q)});Y["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:m.folder,
description:h,descriptionContentType:"text/amz-markdown-sim",extensions:{tt:{assignedGroup:m.group,category:m.category,impact:5,item:m.item,type:m.type}},tags:[{id:"internal-problem-generated"}],title:k}}).then(function(q){D(l,!0,q)}).catch(function(q){D(l,!1,q)});return!1};d.onsubmit=function(h){return t(h)};b=u["default"].cardRoot.querySelector(".p13n-desktop-report-problem-flag-data");if(b.dataset.name)p["default"].on("a:popover:hide:"+b.dataset.name,function(){d.reset();l.innerText=""})},ea=function(a,
c){if(!a.dataset.aCarouselOptions)return z["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions","ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=u["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(d){return JSON.parse(d).id}).slice(b,b+c)},fa=function(a){return(a=a.dataset.asinList)?a.split(","):[]},ha=function(a,c,b,d,e){for(var f="",g=0;g<a.length;g++){var n=a[g];f+=(n?"![]("+n.src+")":
"IMAGE MISSING")+"\nASIN: "+(c[g]?c[g]:"ASIN MISSING")+"\n\n"}return"**This SIM-T ticket is created by the 'Report a Problem' internal tool. To know more, here's its wiki: https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Alias:** ["+(d+"](https://phonetool.amazon.com/users/"+d+")\n**Comment:** "+b+"\n\n**Widget Group ID:** "+e.widgetGroupId+"\n**Strategy ID:** "+e.strategyId+"\n**CTI:** "+e.cti+"\n**Facets:** ")+
(e.facets+"\n**Content Reftag:** "+e.reftag+"\n"+(""!==e.baseAsin?"**Page ASIN:** "+e.baseAsin+"\n":"")+"\n**SessionID:** ")+(e.sessionId+"\n**MarketplaceID:** "+e.marketplaceId+"\n**Device Type:** "+e.deviceType+"\n\n**List of ASINs:**\n\n")+f},D=function(a,c,b){c?(a.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?b.responseBody.response&&b.responseBody.response.id?a.innerHTML="Success, here's the <a href=\"https://t.corp.amazon.com/"+b.responseBody.response.id+
'" target="_blank">SIM-T ticket</a> you created.':(z["default"].log("Fail to find the id of the SIM-T ticket created in the response body of response data.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket."):(z["default"].log("The response body of response data is not an object.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket.")):(a.classList.add("a-color-error"),a.innerText="string"===typeof b?b:"Oops! Something went wrong. Please try again.")},
ja={setupModal:function(a){return r.__awaiter(void 0,void 0,void 0,function(){var c;return r.__generator(this,function(b){c=u["default"].cardRoot.querySelector(".p13n-report-problem-modal-root");if(!c)return[2];ia(a);return[2]})})}},ka=G["default"].setup(["getLazyLoadDeliveryMessage"]),la=function(a){return r.__awaiter(void 0,void 0,void 0,function(){var c,b,d;return r.__generator(this,function(e){switch(e.label){case 0:c=a.querySelectorAll("[data-udm-asin]:not([data-requested=true])");if(!c.length)return[2,
void 0];b=[];c.forEach(function(f){var g=f.dataset.udmAsin,n=f.dataset.udmMerchantId,l=f.dataset.udmBlockSize,t=f.dataset.udmLayoutSize,h="true"===f.dataset.udmBadgeWithoutProgramName;g&&n&&l&&(b.push({asin:g,merchantId:n,blockSize:l,layoutSize:t,badgeWithoutProgramName:h}),f.dataset.requested="true")});return b.length?[4,ka.getLazyLoadDeliveryMessage({lazyLoadDeliveryMessageViewModels:b})]:[2,void 0];case 1:return d=e.sent(),[2,[].slice.call(d.querySelectorAll("[data-udm-asin]:not([data-requested=true])"))]}})})},
ma=function(a){return r.__awaiter(void 0,void 0,void 0,function(){var c;return r.__generator(this,function(b){switch(b.label){case 0:return[4,la(a)];case 1:c=b.sent();if(!c)return[2];c.map(function(d){var e=d.dataset.udmAsin,f=d.dataset.udmMerchantId;e&&f&&(e=a.querySelector("[data-udm-asin="+e+"][data-udm-merchant-id="+f+"]"))&&(e.outerHTML=d.innerHTML)});return[2]}})})},I=[],na=function(a){var c=Array.prototype.slice.call(a.querySelectorAll("[data-metrics]"));c.push(a);c.forEach(function(b){if(b&&
b.dataset&&b.dataset.metrics&&(!b.id||!I.includes(b.id))){var d=JSON.parse(b.dataset.metrics),e;for(e in d)d.hasOwnProperty(e)&&B.count(e,d[e]);b.removeAttribute("data-metrics");b.id&&I.push(b.id)}})},J=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,K=/[^\/\-\[\]():\s]/,oa=function(a){var c=p["default"].$("<div>")[0];c.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||
"2",10),d=function(){var g=a.innerHTML;a.innerHTML="&hellip;";var n=a.clientHeight;a.innerHTML=g;return n}();if(b){if(d){var e=function(g){c.innerHTML=g;return Math.round(c.clientHeight/d)<=b},f=function(g,n){g=g.split(n);var l=Math.floor(a.clientWidth/12),t=function(k){c.classList.add("p13n-sc-offscreen-truncate");c.style.overflow="hidden";c.textContent=k;a.appendChild(c);k=a.clientWidth>=a.scrollWidth;a.removeChild(c);return k},h=function(k){var v=k.length-l;k.trim().length>l&&!t(k)&&Array.prototype.slice.call(k).map(function(m,
q){return q>l&&q<=v&&K.test(m)?"&shy;"+m:m});return k};return g.map(function(k){return h(k)}).join("")};return{truncate:function(){var g=a.innerHTML.trim(),n=a.textContent||"";g=f(g,J);a.appendChild(c);if(e(g))a.removeChild(c),a.innerHTML=g;else{var l=g.split(J);for(var t=1,h=l.length,k,v,m=0;t!==h;)if(k=Math.floor((h+t)/2),v=l.slice(0,k).join("")+"&hellip;",e(v)){if(1>=h-k){for(m=k;0<m&&!K.test(l[m-1]);)m--;break}t=k}else h=k;l=0===m?void 0:l.slice(0,m).join("")+"&hellip;";l?(a.innerHTML=l,a.setAttribute("title",
n),a.setAttribute("aria-label",n)):(z["default"].log("Unable to successfully truncate line "+g,"ERROR"),a.removeChild(c))}}}}z["default"].log("Truncation element does not have a line height or it is zero","ERROR")}else z["default"].log("Truncation element missing necessary line number data","ERROR")},pa=function(a){var c=Array.prototype.slice.call(a.getElementsByClassName("p13n-sc-truncate"));a=a.getElementsByClassName("p13n-sc-truncate-fallback");(window.CSS&&CSS.supports&&CSS.supports("-webkit-line-clamp",
"1")?c:c.concat(Array.prototype.slice.call(a))).filter(function(b){return!!b.offsetParent}).map(function(b){var d=oa(b);d&&(d.truncate(),b.classList.add("p13n-sc-truncated"),b.classList.remove("p13n-sc-truncate"),b.classList.remove("p13n-sc-truncate-fallback"),b.className=b.className.replace(/p13n-sc-line-clamp-\d/g,""))})},qa=function(a){a.querySelectorAll(".a-carousel-viewport").forEach(function(c){c=c.querySelectorAll(".a-carousel-card");for(var b=null,d=0;d<c.length;d++){var e=c[d].getAttribute("aria-roledescription");
if(null!==e&&""!==e){b=e;break}}b=b||"slide";c.forEach(function(f){f.getAttribute("aria-roledescription")!==b&&f.setAttribute("aria-roledescription",b)})})},wa={initCarousel:function(a){return r.__awaiter(void 0,void 0,void 0,function(){var c,b,d;return r.__generator(this,function(e){c=(a||{}).afterPageLoaded;b=u["default"].cardRoot.classList.contains("p13n-sc-shoveler")?[u["default"].cardRoot]:Array.prototype.slice.call(u["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler"));d=G["default"].setup(["getCarouselItems"]);
if(null===b||void 0===b||!b.length)return[2];b.forEach(function(f){return r.__awaiter(void 0,void 0,void 0,function(){var g,n,l,t,h,k;return r.__generator(this,function(v){switch(v.label){case 0:g=f.dataset||{};n="true"===g.showlazyloaddeliverymessage;l=function(){p["default"].loadDynamicImage("[data-name]='"+k+"' .p13n-sc-dynamic-image");pa(f);na(f);null===c||void 0===c?void 0:c(f);var m=window.P;aa(m);ba(m);qa(f);n&&ma(f)};l();if(f.classList.contains("p13n-carousel-initialized"))return[2];f.classList.add("p13n-carousel-initialized");
t=X["default"].getCarousel(P.unscope(f));h=W["default"].getCarousel(f);k=t.getAttr("name");return[4,Promise.all([h.initialized,ja.setupModal(f)])];case 1:return v.sent(),p["default"].on("a:carousel:"+k+":change:pageSize",l),p["default"].on("a:carousel:"+k+":change:loading",l),p["default"].on("a:carousel:"+k+":change:animating",l),p["default"].on("a:carousel:"+k+":change:fetchedItems",l),h.attachRemoteOperation(function(m){var q=m.indexes;m=m.ids;var L=d,ra=L.getCarouselItems,sa=r.__assign,ta=r.__assign({},
g),ua=String(q[0]||0);var va=q[0]||0,y,E,M=0,w=g.aCarouselOptions?g.aCarouselOptions:void 0;if(w&&(w=JSON.parse(w),w=null===(y=null===w||void 0===w?void 0:w.ajax)||void 0===y?void 0:y.id_list))for(y=0;y<va&&y<w.length;y++){var A=JSON.parse(w[y]);"true"===((null===(E=null===A||void 0===A?void 0:A.metadataMap)||void 0===E?0:E.isSponsoredProduct)?A.metadataMap.isSponsoredProduct:"false")&&(M+=1)}return ra.call(L,sa.call(r,ta,{ids:m,indexes:q,offset:ua,adOffset:M}))}),[2]}})})});return[2]})})}};F._operationNames=
["getCarouselItems"];F.card=function(){return r.__awaiter(void 0,void 0,void 0,function(){return r.__generator(this,function(a){switch(a.label){case 0:return[4,wa.initCarousel()];case 1:return a.sent(),[2]}})})}});
